### ISSUE TITLE
編修建議

### ISSUE THREAD

**Issue by Kishibe3** [ruhuasiyu/VanillaModToturial#1]
您真的是創造了一篇高品質的教程，我感到敬佩不已。
只是目前有些章節仍未完善，雖然有副標題但我其實猜不太出一些章節的內容(水處理、地獄處理、重生成、字符操作等等)。請問能不能分享一下這些未來會加入的內容？(可能發個文簡述大略內容)我其實非常好奇究竟維度模擬能做到多大程度。

**Comment by zhangshenxing** [comment]
> 
> 
> 您真的是創造了一篇高品質的教程，我感到敬佩不已。
> 只是目前有些章節仍未完善，雖然有副標題但我其實猜不太出一些章節的內容(水處理、地獄處理、重生成、字符操作等等)。請問能不能分享一下這些未來會加入的內容？(可能發個文簡述大略內容)我其實非常好奇究竟維度模擬能做到多大程度。

1.16 已经可以自定义维度了
